
version: '3.8'

services:
  mysql-server:
    image: mysql:latest

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderfy_auth
      MYSQL_USER: orderfy
      MYSQL_PASSWORD: root

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: # Define o volume nomeado